/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.sql.Connection;
import java.sql.DriverManager;
import com.mysql.cj.jdbc.CallableStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author HAPPY
 */
public class Main_Frame extends javax.swing.JFrame {

    private Thread clockThread;

    /**
     * Creates new form Main_Frame
     */
    public Main_Frame() {
        initComponents();
    }

    public void updateCounts(int soLuongHocVien, int soLuongGiangVien, int soLuongKhoaHoc) {
        tonghocvien.setText(String.valueOf(soLuongHocVien));
        tonggiangvien.setText(String.valueOf(soLuongGiangVien));
        tongkhoahoc.setText(String.valueOf(soLuongKhoaHoc));
    }

    void updateClock() {
        clockThread = new Thread(() -> {
            while (true) {
                SimpleDateFormat dateFormat = new SimpleDateFormat("HH:mm:ss - dd/MM/yyyy");
                String dateTime = dateFormat.format(new Date());
                timeLabel.setText("" + dateTime);

                try {
                    Thread.sleep(1000); // Cập nhật giờ mỗi giây
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        });
        clockThread.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tk = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tonghocvien = new javax.swing.JLabel();
        tonggiangvien = new javax.swing.JLabel();
        tongkhoahoc = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        doimatkhau = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        trangchu = new javax.swing.JLabel();
        quanly = new javax.swing.JLabel();
        khoahoc = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ TRUNG TÂM NGOẠI NGỮ");
        setMaximumSize(new java.awt.Dimension(1300, 800));
        setMinimumSize(new java.awt.Dimension(1300, 800));
        setPreferredSize(new java.awt.Dimension(1300, 800));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tk.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tk.setForeground(new java.awt.Color(255, 255, 255));
        tk.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tkAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        getContentPane().add(tk, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 130, 120, 40));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Tài khoản đăng nhập");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 110, -1, -1));

        tonghocvien.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        tonghocvien.setForeground(new java.awt.Color(204, 0, 51));
        tonghocvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tonghocvienMouseClicked(evt);
            }
        });
        getContentPane().add(tonghocvien, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 70, 70));

        tonggiangvien.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        tonggiangvien.setForeground(new java.awt.Color(204, 0, 51));
        tonggiangvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tonggiangvienMouseClicked(evt);
            }
        });
        getContentPane().add(tonggiangvien, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, 70, 70));

        tongkhoahoc.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        tongkhoahoc.setForeground(new java.awt.Color(204, 0, 51));
        tongkhoahoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tongkhoahocMouseClicked(evt);
            }
        });
        getContentPane().add(tongkhoahoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 540, 70, 70));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 0, 204));
        jLabel16.setText("SỐ HỌC VIÊN");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 270, 70));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 0, 204));
        jLabel17.setText("SỐ G.VIÊN");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 230, 70));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 0, 204));
        jLabel18.setText("SỐ K.HỌC");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 480, 230, 70));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("THÔNG TIN TRUNG TÂM");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 450, 60));

        jLabel3.setBackground(new java.awt.Color(204, 255, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trang.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 260, 150));

        jLabel14.setBackground(new java.awt.Color(204, 255, 0));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trang.jpg"))); // NOI18N
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 490, 260, 150));

        jLabel15.setBackground(new java.awt.Color(204, 255, 0));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trang.jpg"))); // NOI18N
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 490, 260, 150));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 102));
        jLabel10.setText("IELTS ");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 240, 230, 70));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 102));
        jLabel12.setText("TOEIC 650+");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 230, 70));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 102));
        jLabel11.setText("TOEIC 450+");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 230, 70));

        jLabel5.setBackground(new java.awt.Color(204, 255, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trang.jpg"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 220, 260, 110));

        jLabel4.setBackground(new java.awt.Color(204, 255, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trang.jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 260, 110));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("KHOÁ HỌC NỔI BẬT");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 370, 60));

        jLabel2.setBackground(new java.awt.Color(204, 255, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trang.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 260, 110));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Giờ hệ thống");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 170, 40));

        timeLabel.setBackground(new java.awt.Color(255, 51, 0));
        timeLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(timeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 280, 50));

        doimatkhau.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        doimatkhau.setText("MẬT KHẨU");
        doimatkhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doimatkhauMouseClicked(evt);
            }
        });
        getContentPane().add(doimatkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, 160, 90));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("HỆ THỐNG QUẢN LÝ TRUNG TÂM NGOẠI NGỮ");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 880, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel6.setText("ĐỔI ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, 50, 90));

        trangchu.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        trangchu.setText("TRANG CHỦ");
        trangchu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trangchuMouseClicked(evt);
            }
        });
        getContentPane().add(trangchu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 120, 40));

        quanly.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        quanly.setText("QUẢN LÝ");
        quanly.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quanlyMouseClicked(evt);
            }
        });
        getContentPane().add(quanly, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 120, 40));

        khoahoc.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        khoahoc.setText("KHOÁ HỌC");
        khoahoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                khoahocMouseClicked(evt);
            }
        });
        getContentPane().add(khoahoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg_main.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1580, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void trangchuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trangchuMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_trangchuMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void tonghocvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tonghocvienMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tonghocvienMouseClicked

    private void tonggiangvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tonggiangvienMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tonggiangvienMouseClicked

    private void tongkhoahocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tongkhoahocMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tongkhoahocMouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseClicked

    private void quanlyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quanlyMouseClicked
        Quanly_Frame ql = new Quanly_Frame();
        ql.updateClock();
        ql.setVisible(true);
    }//GEN-LAST:event_quanlyMouseClicked

    private void khoahocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khoahocMouseClicked
        // TODO add your handling code here:
        Ql_KH_Frame kh = new Ql_KH_Frame();
        kh.updateClock();
        kh.setVisible(true);
    }//GEN-LAST:event_khoahocMouseClicked

    private void doimatkhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doimatkhauMouseClicked
        // TODO add your handling code here:
        Doi_MK_Frame doimk = new Doi_MK_Frame();
        doimk.updateClock();
        doimk.setVisible(true);
    }//GEN-LAST:event_doimatkhauMouseClicked

    private void tkAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tkAncestorAdded
        // TODO add your handling code here:
        if (!Login_Frame.getLoggedInUsername().equals("")) {
            tk.setText(Login_Frame.getLoggedInUsername());
        } else {
            tk.setText("Not User");
        }
    }//GEN-LAST:event_tkAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main_Frame mainFrame = new Main_Frame();
                mainFrame.updateClock();
                mainFrame.setVisible(true);
                // Kết nối đến cơ sở dữ liệu MySQL
                String url = "jdbc:mysql://localhost:3306/ql_lop_av";
                String user = "root";
                String password = "";
                try (Connection connection = DriverManager.getConnection(url, user, password)) {
                    // Gọi funtion để lấy số lượng học viên
                    CallableStatement cs1 = (CallableStatement) connection.prepareCall("{? = call DemSoLuongHocVien()}");
                    cs1.registerOutParameter(1, java.sql.Types.INTEGER);
                    cs1.execute();
                    int soLuongHocVien = cs1.getInt(1);

                    // Gọi funtion để lấy số lượng giảng viên
                    CallableStatement cs2 = (CallableStatement) connection.prepareCall("{? = call DemSoLuongGiangVien()}");
                    cs2.registerOutParameter(1, java.sql.Types.INTEGER);
                    cs2.execute();
                    int soLuongGiangVien = cs2.getInt(1);

                    // Gọi funtion để lấy số lượng khóa học
                    CallableStatement cs3 = (CallableStatement) connection.prepareCall("{? = call DemSoLuongKhoaHoc()}");
                    cs3.registerOutParameter(1, java.sql.Types.INTEGER);
                    cs3.execute();
                    int soLuongKhoaHoc = cs3.getInt(1);

                    // Đặt giá trị cho các JLabel
                    mainFrame.tonghocvien.setText(String.valueOf(soLuongHocVien));
                    mainFrame.tonggiangvien.setText(String.valueOf(soLuongGiangVien));
                    mainFrame.tongkhoahoc.setText(String.valueOf(soLuongKhoaHoc));

                } catch (SQLException e) {
                    e.printStackTrace();
                }

            }

        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel doimatkhau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel khoahoc;
    private javax.swing.JLabel quanly;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel tk;
    private javax.swing.JLabel tonggiangvien;
    private javax.swing.JLabel tonghocvien;
    private javax.swing.JLabel tongkhoahoc;
    private javax.swing.JLabel trangchu;
    // End of variables declaration//GEN-END:variables
}
