/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import com.mysql.cj.jdbc.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import com.mysql.cj.jdbc.CallableStatement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author HAPPY
 */
public class Quanly_Frame extends javax.swing.JFrame {

    private Thread clockThread;

    /**
     * Creates new form Main_Frame
     */
    public Quanly_Frame() {
        initComponents();
    }

    void updateClock() {
        clockThread = new Thread(() -> {
            while (true) {
                SimpleDateFormat dateFormat = new SimpleDateFormat("HH:mm:ss - dd/MM/yyyy");
                String dateTime = dateFormat.format(new Date());
                timeLabel.setText("" + dateTime);

                try {
                    Thread.sleep(1000); // Cập nhật giờ mỗi giây
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        });
        clockThread.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        ql_giangvien = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ql_hocvien = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        doimatkhau = new javax.swing.JLabel();
        trangchu = new javax.swing.JLabel();
        quanly = new javax.swing.JLabel();
        khoahoc = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ TRUNG TÂM NGOẠI NGỮ");
        setMaximumSize(new java.awt.Dimension(1300, 800));
        setMinimumSize(new java.awt.Dimension(1300, 800));
        setPreferredSize(new java.awt.Dimension(1300, 800));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(204, 255, 0));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/teacher.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 340, 140, 150));

        ql_giangvien.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        ql_giangvien.setText("G.VIÊN");
        ql_giangvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ql_giangvienMouseClicked(evt);
            }
        });
        getContentPane().add(ql_giangvien, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 470, 140, 70));

        jLabel5.setBackground(new java.awt.Color(204, 255, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trang.jpg"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, 200, 240));

        ql_hocvien.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        ql_hocvien.setText("HỌC VIÊN");
        ql_hocvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ql_hocvienMouseClicked(evt);
            }
        });
        getContentPane().add(ql_hocvien, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 270, 70));

        jLabel4.setBackground(new java.awt.Color(204, 255, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/student.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 140, 150));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("QUẢN LÝ THÔNG TIN");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 610, 60));

        jLabel3.setBackground(new java.awt.Color(204, 255, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trang.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 200, 240));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));
        jLabel8.setText("Giờ hệ thống");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 170, 40));

        timeLabel.setBackground(new java.awt.Color(255, 51, 0));
        timeLabel.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(timeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 280, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("HỆ THỐNG QUẢN LÝ TRUNG TÂM NGOẠI NGỮ");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 880, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel6.setText("ĐỔI ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, 50, 90));

        doimatkhau.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        doimatkhau.setText("MẬT KHẨU");
        doimatkhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doimatkhauMouseClicked(evt);
            }
        });
        getContentPane().add(doimatkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, 160, 90));

        trangchu.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        trangchu.setText("TRANG CHỦ");
        trangchu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trangchuMouseClicked(evt);
            }
        });
        getContentPane().add(trangchu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 120, 40));

        quanly.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        quanly.setText("QUẢN LÝ");
        quanly.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quanlyMouseClicked(evt);
            }
        });
        getContentPane().add(quanly, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 120, 50));

        khoahoc.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        khoahoc.setText("KHOÁ HỌC");
        khoahoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                khoahocMouseClicked(evt);
            }
        });
        getContentPane().add(khoahoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg_main.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1280, 800));
        jLabel1.setMinimumSize(new java.awt.Dimension(1280, 800));
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 800));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1280, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void trangchuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trangchuMouseClicked
        try {
            // Tạo kết nối đến cơ sở dữ liệu MySQL
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/ql_lop_av", "root", "");

            // Gọi funtion để lấy số lượng học viên
            CallableStatement cs1 = (CallableStatement) conn.prepareCall("{? = call DemSoLuongHocVien()}");
            cs1.registerOutParameter(1, java.sql.Types.INTEGER);
            cs1.execute();
            int soLuongHocVien = cs1.getInt(1);

            // Gọi funtion để lấy số lượng giảng viên
            CallableStatement cs2 = (CallableStatement) conn.prepareCall("{? = call DemSoLuongGiangVien()}");
            cs2.registerOutParameter(1, java.sql.Types.INTEGER);
            cs2.execute();
            int soLuongGiangVien = cs2.getInt(1);

            // Gọi funtion để lấy số lượng khóa học
            CallableStatement cs3 = (CallableStatement) conn.prepareCall("{? = call DemSoLuongKhoaHoc()}");
            cs3.registerOutParameter(1, java.sql.Types.INTEGER);
            cs3.execute();
            int soLuongKhoaHoc = cs3.getInt(1);

            // Tạo một instance của Main_Frame
            Main_Frame main = new Main_Frame();

            // Cập nhật số lượng học viên, giảng viên và khóa học
            main.updateCounts(soLuongHocVien, soLuongGiangVien, soLuongKhoaHoc);

            main.updateClock();
            main.setVisible(true);
            this.setVisible(false);

            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi kết nối cơ sở dữ liệu: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_trangchuMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void ql_hocvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ql_hocvienMouseClicked
        // TODO add your handling code here:
        Ql_HV_Frame hv = new Ql_HV_Frame();
        hv.updateClock();
        hv.setVisible(true);
                
    }//GEN-LAST:event_ql_hocvienMouseClicked

    private void quanlyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quanlyMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_quanlyMouseClicked

    private void ql_giangvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ql_giangvienMouseClicked
        // TODO add your handling code here:
        Ql_GV_Frame gv = new Ql_GV_Frame();
        gv.updateClock();
        gv.setVisible(true);
    }//GEN-LAST:event_ql_giangvienMouseClicked

    private void khoahocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_khoahocMouseClicked
        // TODO add your handling code here:
        Ql_KH_Frame kh = new Ql_KH_Frame();
        kh.updateClock();
        kh.setVisible(true);
    }//GEN-LAST:event_khoahocMouseClicked

    private void doimatkhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doimatkhauMouseClicked
        // TODO add your handling code here:
        Doi_MK_Frame mk = new Doi_MK_Frame();
        mk.setVisible(true);
        mk.updateClock();
    }//GEN-LAST:event_doimatkhauMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quanly_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quanly_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quanly_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quanly_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Quanly_Frame mainFrame = new Quanly_Frame();
                mainFrame.updateClock();
                mainFrame.setVisible(true);

            }

        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel doimatkhau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel khoahoc;
    private javax.swing.JLabel ql_giangvien;
    private javax.swing.JLabel ql_hocvien;
    private javax.swing.JLabel quanly;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel trangchu;
    // End of variables declaration//GEN-END:variables
}
